provision.sh: avoid endless while loop
Fixes: https://github.com/SUSE/sesdev/issues/362
Signed-off-by: Nathan Cutler <ncutler@suse.com>

diff --git a/seslib/templates/provision.sh.j2 b/seslib/templates/provision.sh.j2
--- a/seslib/templates/provision.sh.j2
+++ b/seslib/templates/provision.sh.j2
@@ -76,7 +76,12 @@ EOF
 chmod 755 {{ devel_repo_script }}
 
 {% if devel_repo or not core_version %}
-{{ devel_repo_script }}
+if {{ devel_repo_script }} ; then
+    true
+else
+    echo "{{ devel_repo_script }} failed! Bailing out."
+    exit 1
+fi
 {% endif %}
 
 {% if os.startswith("sle") %}
@@ -178,8 +183,11 @@ systemctl restart salt-minion
 
 set +x
 rm -f /tmp/ready-*
+count="0"
+max_count_we_tolerate="50"
 echo "Waiting for {{ nodes | length }} nodes to complete initial provisioning..."
 while true ; do
+  count="$((count + 1))"
 {% for node in nodes %}
   scp -o StrictHostKeyChecking=no {{ node.name }}:/tmp/ready /tmp/ready-{{ node.name }} || true
 {% endfor %}
@@ -187,8 +195,12 @@ while true ; do
   echo "${PROVISIONED_NODES} of {{ nodes | length }} have completed initial provisioning."
   [ "${PROVISIONED_NODES}" = "{{ nodes|length }}" ] && break
   set -x
-  sleep 3
+  sleep 5
   set +x
+  if [ "$count" -gt "$max_count_we_tolerate" ] ; then
+      echo "Looped too many times. Something is wrong. Bailing out!"
+      exit 1
+  fi
 done
 set -x
 
