ceph_salt_deployment: prevent Vagrant from deleting master node
As of some recent version of Vagrant, it started removing the master
domain (i.e., destroying the master node) whenever the provisioning
script exited with a code other than "0".

Deleting the master node makes it impossible to investigate why the
script failed.

I can't think of any good reason for Vagrant/vagrant-libvirt to behave
like this. It's a recent development. I don't know how to turn the
behavior off, but I can at least work around it by preventing the
deployment script from returning any exit code other than 0.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

diff --git a/seslib/templates/provision.sh.j2 b/seslib/templates/provision.sh.j2
--- a/seslib/templates/provision.sh.j2
+++ b/seslib/templates/provision.sh.j2
@@ -1,6 +1,19 @@
-{% include "engine/" + vm_engine + "/vagrant.provision.sh.j2" ignore missing %}
-
 set -ex
+
+DEPLOYMENT_SCRIPT="$0"
+
+function err_report {
+    local line_number="$1"
+    echo "Error in sesdev deployment script trapped!"
+    echo "=> hostname: $(hostname)"
+    echo "=> script: $DEPLOYMENT_SCRIPT"
+    echo "=> line number: $line_number"
+    echo "Bailing out!"
+    exit 0
+}
+
+# ensure Vagrant doesn't destroy the master node when the script fails
+trap 'err_report $LINENO' ERR
 
 ls -lR /home/vagrant
 
