ceph_salt_deployment: prevent Vagrant from deleting master node
As of some recent version of Vagrant, it started removing the master
domain (i.e., destroying the master node) whenever the provisioning
script exited with a code other than "0".

Deleting the master node makes it impossible to investigate why the
script failed.

I can't think of any good reason for Vagrant/vagrant-libvirt to behave
like this. It's a recent development. I don't know how to turn the
behavior off, but I can at least work around it by preventing the
deployment script from returning any exit code other than 0.

Signed-off-by: Nathan Cutler <ncutler@suse.com>

diff --git a/seslib/templates/salt/wait_for_minions.j2 b/seslib/templates/salt/wait_for_minions.j2
--- a/seslib/templates/salt/wait_for_minions.j2
+++ b/seslib/templates/salt/wait_for_minions.j2
@@ -1,19 +1,20 @@
 
 # make sure all minions are responding
-set +ex
+set +x
 LOOP_COUNT="0"
 while true ; do
   if [ "$LOOP_COUNT" -ge "30" ] ; then
-    echo "ERROR: minion(s) not responding to ping?"
-    exit 1
+    echo "ERROR: minion(s) failed to respond to ping. Bailling out!"
+    set -e
+    false
   fi
   LOOP_COUNT="$((LOOP_COUNT + 1))"
   echo "Pinging {{ nodes | length }} minions..."
-  MINIONS_RESPONDING="$(salt '*' test.ping 2> /dev/null | grep --count True)"
+  MINIONS_RESPONDING="$(salt '*' test.ping 2> /dev/null | grep --count True || true)"
   echo "${MINIONS_RESPONDING} of {{ nodes | length }} minions responded to ping."
   [ "$MINIONS_RESPONDING" = "{{ nodes|length }}" ] && break
   set -x
   sleep 3
   set +x
 done
-set -ex
+set -x
