seslib: if `ceph status` fails, dump contents of /etc/ceph/
Signed-off-by: Tim Serong <tserong@suse.com>

diff --git a/seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2 b/seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
--- a/seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
+++ b/seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
@@ -186,21 +186,12 @@ fi
 set -x
 
 set +x
-timeout_seconds="60"
-remaining_seconds="$timeout_seconds"
-interval_seconds="5"
-while true ; do
-    [ -r /etc/ceph/ceph.client.admin.keyring ] && break
-    remaining_seconds="$(( remaining_seconds - interval_seconds ))"
-    if [ "$remaining_seconds" -le "0" ] ; then
-        echo "It seems unlikely that /etc/ceph/ceph.client.admin.keyring will ever appear. Bailing out!"
-        echo "$(ls -l /etc/ceph)"
-        false
-    fi
-    echo "..."
-    sleep "$interval_seconds"
-done
+if ! ceph status ; then
+    echo "\"ceph status\" failed"
+    ls -l /etc/ceph
+    for f in /etc/ceph/* ; do
+        echo $f
+        cat $f
+    done
+fi
 set -x
-
-ceph status
-echo "\"ceph status\" exit code: $?"
