ses5_pre_stage_0: do not fail easily on test.ping
Signed-off-by: Nathan Cutler <ncutler@suse.com>

diff --git a/seslib/templates/deepsea/ses5_pre_stage_0.sh.j2 b/seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
--- a/seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
+++ b/seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
@@ -23,9 +23,26 @@ sed -i 's/#worker_threads: 5/worker_threads: 10/g' /etc/salt/master
 systemctl restart salt-master
 systemctl restart salt-minion
 
-sleep 10
-
-salt '*' test.ping
+# make sure all minions are responding
+set +ex
+LOOP_COUNT="0"
+while true ; do
+  set -x
+  sleep 5
+  set +x
+  if [ "$LOOP_COUNT" -ge "20" ] ; then
+    echo "ERROR: minion(s) not responding to ping?"
+    exit 1
+  fi
+  LOOP_COUNT="$((LOOP_COUNT + 1))"
+  set -x
+  MINIONS_RESPONDING="$(salt '*' test.ping | grep True | wc --lines)"
+  if [ "$MINIONS_RESPONDING" = "{{ nodes|length }}" ]; then
+    break
+  fi
+  set +x
+done
+set -ex
 
 cat > /srv/salt/ceph/updates/nop.sls <<EOF
 dummy command:
